function Update_VALR(VALR)
%input:
%   Rest_Step(number)
%output:
% 
%function:
% Display the left step number on exploration stage
hold on;
persistent x;
persistent h0;
persistent h1;

if isempty(x)
    x=0;
    h1=annotation('textbox',...
        [0.79 0.5 0.08,0.08],...
        'String',{['Ð±ÂÊ£º' num2str(VALR) ]},...
        'Fontsize',30,...
        'FontName','STFangSong',...
        'LineStyle','--',...
        'EdgeColor',[1 1 1],...
        'LineWidth',2,...
        'BackgroundColor',[1  1 1],...
        'Color',[0.84 0.16 0]);
end

switch x
    case 0
        delete(h1);
        h0=annotation('textbox',...
            [0.79 0.5 0.08,0.08],...
            'String',{['Ð±ÂÊ£º' num2str(VALR) ]},...
            'Fontsize',30,...
            'FontName','STFangSong',...
            'LineStyle','--',...
            'EdgeColor',[1 1 1],...
            'LineWidth',2,...
            'BackgroundColor',[1  1 1],...
            'Color',[0.84 0.16 0]);
        x = 1;
    case 1
        delete(h0);
        h1=annotation('textbox',...
            [0.79 0.5 0.08,0.08],...
            'String',{['Ð±ÂÊ£º' num2str(VALR) ]},...
            'Fontsize',30,...
            'FontName','STFangSong',...
            'LineStyle','--',...
            'EdgeColor',[1 1 1],...
            'LineWidth',2,...
            'BackgroundColor',[1  1 1],...
            'Color',[0.84 0.16 0]);
        x = 0;
        
end
drawnow;

